/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedPulseRouteImport } from './routes/_authenticated/pulse'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLensRouteImport } from './routes/_authenticated/lens'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPulseIndexRouteImport } from './routes/_authenticated/pulse.index'
import { Route as AuthenticatedStoryIdRouteImport } from './routes/_authenticated/story.$id'
import { Route as AuthenticatedPulseSymbolRouteImport } from './routes/_authenticated/pulse.$symbol'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPulseRoute = AuthenticatedPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLensRoute = AuthenticatedLensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPulseIndexRoute = AuthenticatedPulseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPulseRoute,
} as any)
const AuthenticatedStoryIdRoute = AuthenticatedStoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPulseSymbolRoute =
  AuthenticatedPulseSymbolRouteImport.update({
    id: '/$symbol',
    path: '/$symbol',
    getParentRoute: () => AuthenticatedPulseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/lens': typeof AuthenticatedLensRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/pulse': typeof AuthenticatedPulseRouteWithChildren
  '/saved': typeof AuthenticatedSavedRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/pulse/$symbol': typeof AuthenticatedPulseSymbolRoute
  '/story/$id': typeof AuthenticatedStoryIdRoute
  '/pulse/': typeof AuthenticatedPulseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/lens': typeof AuthenticatedLensRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/pulse/$symbol': typeof AuthenticatedPulseSymbolRoute
  '/story/$id': typeof AuthenticatedStoryIdRoute
  '/pulse': typeof AuthenticatedPulseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/lens': typeof AuthenticatedLensRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/pulse': typeof AuthenticatedPulseRouteWithChildren
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/pulse/$symbol': typeof AuthenticatedPulseSymbolRoute
  '/_authenticated/story/$id': typeof AuthenticatedStoryIdRoute
  '/_authenticated/pulse/': typeof AuthenticatedPulseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/admin'
    | '/daily'
    | '/lens'
    | '/profile'
    | '/pulse'
    | '/saved'
    | '/voice'
    | '/api/chat'
    | '/pulse/$symbol'
    | '/story/$id'
    | '/pulse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/admin'
    | '/daily'
    | '/lens'
    | '/profile'
    | '/saved'
    | '/voice'
    | '/api/chat'
    | '/pulse/$symbol'
    | '/story/$id'
    | '/pulse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/daily'
    | '/_authenticated/lens'
    | '/_authenticated/profile'
    | '/_authenticated/pulse'
    | '/_authenticated/saved'
    | '/_authenticated/voice'
    | '/api/chat'
    | '/_authenticated/pulse/$symbol'
    | '/_authenticated/story/$id'
    | '/_authenticated/pulse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pulse': {
      id: '/_authenticated/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AuthenticatedPulseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lens': {
      id: '/_authenticated/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof AuthenticatedLensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pulse/': {
      id: '/_authenticated/pulse/'
      path: '/'
      fullPath: '/pulse/'
      preLoaderRoute: typeof AuthenticatedPulseIndexRouteImport
      parentRoute: typeof AuthenticatedPulseRoute
    }
    '/_authenticated/story/$id': {
      id: '/_authenticated/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof AuthenticatedStoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pulse/$symbol': {
      id: '/_authenticated/pulse/$symbol'
      path: '/$symbol'
      fullPath: '/pulse/$symbol'
      preLoaderRoute: typeof AuthenticatedPulseSymbolRouteImport
      parentRoute: typeof AuthenticatedPulseRoute
    }
  }
}

interface AuthenticatedPulseRouteChildren {
  AuthenticatedPulseSymbolRoute: typeof AuthenticatedPulseSymbolRoute
  AuthenticatedPulseIndexRoute: typeof AuthenticatedPulseIndexRoute
}

const AuthenticatedPulseRouteChildren: AuthenticatedPulseRouteChildren = {
  AuthenticatedPulseSymbolRoute: AuthenticatedPulseSymbolRoute,
  AuthenticatedPulseIndexRoute: AuthenticatedPulseIndexRoute,
}

const AuthenticatedPulseRouteWithChildren =
  AuthenticatedPulseRoute._addFileChildren(AuthenticatedPulseRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedLensRoute: typeof AuthenticatedLensRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPulseRoute: typeof AuthenticatedPulseRouteWithChildren
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedStoryIdRoute: typeof AuthenticatedStoryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedLensRoute: AuthenticatedLensRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPulseRoute: AuthenticatedPulseRouteWithChildren,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedStoryIdRoute: AuthenticatedStoryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
